.TH CD 1
.SH CD
chdir \- change the current working directory
.SH SYNOPSIS
.B cd
[
.I \-h
]
[
.I \-\-help
]
.SH "DESCRIPTION"
Changes the current working directory to the one specified
.SH OPTIONS
.TP
.B "\-a, \-\-author"
Print the version information of TechOS.
.TP
.B \-h, \-\-help
Show a short usage message
.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Jared Miller, Lucas Darnell and Benjamin Culkin
