.TH DATEFMT 1
.SH DATEFMT
datefmt \- show date in a specific format
.SH SYNOPSIS
.B datefmt
.SH "DESCRIPTION"
.BR datefmt
Show date in a specific format, and it can be changed using specific options 
.SH OPTIONS
.TP
.B \-i, \-\-help, \-s, \-d, \-o

.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Jared Miller, Lucas Darnell and Benjamin Culkin
