.TH DATEFMT 1
.SH NAME
datefmt \- show date in a specific format
.SH SYNOPSIS
.B datefmt 
[
.I -stdioh
]
[
.I --help
]
[
.I --set | --display
]
[
.I --time | --in --out
]

.SH "DESCRIPTION"
Show date in a specific format, and it can be changed using the -s argument.

.SH "SPECIAL CHARACTERS"

.TP
.B %a
The  abbreviated  name	of  the day of the week according to the current locale.
.TP
.B %A
The full name of the day of the week according  to  the  current locale.
.TP
.B %b
The abbreviated month name according to the current locale.
.TP
.B %B
The full month name according to the current locale.
.TP
.B %c
The  preferred  date  and  time  representation  for the current locale.
.TP
.B %C
The century number (year/100) as a 2-digit integer. (SU)
.TP
.B %d
The day of the month as a decimal number (range 01 to 31).
.TP
.B %D
Equivalent to %m/%d/%y. (Yecch — for Americans only. Americans should note
that in other countries %d/%m/%y is rather common. This means that in
international context this format is ambiguous and should not be used.) (SU)
.TP
.B %e
Like %d, the day of the month as a decimal number, but a leading zero is
replaced by a space. (SU)
.TP
.B %E
Modifier: use alternative format, see below. (SU)
.TP
.B %F
Equivalent to \fB%Y-%m-%d\fR (the ISO 8601 date format). (C99)
.TP
.B %G
The ISO 8601 week-based year (see NOTES) with century as a decimal number.
The 4-digit year corresponding to the ISO week number (see %V).  This has the
same format and value as %Y, except that if the  ISO  week number belongs
to the previous or next year, that year is used instead. (TZ)
.TP
.B %g
Like %G, but without century, that is, with a 2-digit year (00-99). (TZ)
.TP
.B %h
Equivalent to %b. (SU)
.TP
.B %H
The hour as a decimal number using a 24-hour clock (range 00 to 23).
.TP
.B %I
The hour as a decimal number using a 12-hour clock (range 01  to 12).
.TP
.B %j
The day of the year as a decimal number (range 001 to 366).
.TP
.B %k
The hour (24-hour clock) as a decimal number (range 0 to 23); single digits
are preceded by a blank. (See also %H.) (TZ)
.TP
.B %l
The hour (12-hour clock) as a decimal number (range 1 to 12); single digits
are preceded by a blank. (See also %I.) (TZ)
.TP
.B %m
The month as a decimal number (range 01 to 12).
.TP
.B %M 
The minute as a decimal number (range 00 to 59).
.TP
.B %n
A newline character. (SU)
.TP
.B %O
Modifier: use alternative format, see below. (SU)
.TP
.B %p
Either "AM" or "PM" according to the given time value, or the corresponding
strings for the current locale. Noon is treated as "PM" and midnight as "AM".
.TP
.B %P
Like %p but in lowercase: "am" or "pm" or a corresponding string for the current
locale. (GNU)
.TP
.B %r
The time in a.m. or p.m. notation. In the POSIX locale this is equivalent to
%I:%M:%S %p. (SU)
.TP
.B %R
The time in 24-hour notation (%H:%M). (SU) For a version including the seconds,
see %T below.
.TP
.B %s
The number of seconds since the Epoch, 1970-01-01 00:00:00 +0000 (UTC). (TZ)
.TP
.B %S
The second as a decimal number (range 00 to 60). (The range is up to 60 to allow
for occasional leap seconds.)
.TP
.B %t
A tab character. (SU)
.TP
.B %T
The time in 24-hour notation (%H:%M:%S). (SU)
.TP
.B %u
The day of the week as a decimal, range 1 to 7, Monday being 1. See also %w. (SU)
.TP
.B %U
The week number of the current year as a decimal number, range 00 to 53,
starting with the first Sunday as the first day of week 01. See also %V and %W.
.TP
.B %V
The ISO 8601 week number (see NOTES) of the current year as a decimal number,
range 01 to 53, where week 1 is the first week that has at least 4 days in the
new year. See also %U and %W. (SU)
.TP
.B %w
The day of the week as a decimal, range 0 to 6, Sunday being 0. See also %u.
.TP
.B %W
The week number of the current year as a decimal number, range 00 to 53,
starting with the first Monday as the first day of week 01.
.TP
.B %x
The preferred date representation for the current locale without the time.
.TP
.B %X
The preferred time representation for the current locale without the date.
.TP
.B %y
The year as a decimal number without a century (range 00 to 99).
.TP
.B %Y
The year as a decimal number including the century.
.TP
.B %z
The +hhmm or -hhmm numeric timezone (that is, the hour and minute offset from
UTC). (SU)
.TP
.B %Z
The timezone name or abbreviation.
.TP
.B %+
The date and time in date(1) format. (TZ) (Not supported in glibc2.)
.TP
.B %%
A literal '%' character.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show a short usage message.
.TP
.B \-s, \-\-set
Set a format.
.TP
.B \-d, \-\-display
Display a format.
.TP
.B \-t, \-\-time
Operate on the time format.
.TP
.B \-i, \-\-in
Operate on the input date format.
.TP
.B \-o, \-\-out
Operate on the output date format.

.SH EXAMPLES
The example below will return the current format:

.RS
.B TechOS(?)>
.I datefmt   

.RE
The example below will set the date format to the RFC 2822-complient date:
format (ex. "Wed, 06 Sep 2017 19:05:17 -0400")

.RS
.B TechOS(?)>
.I datefmt\ \-s

.B Enter the new format:
.I %a,\ %d\ %b\ %Y\ %T\ %z

.RE
.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Lucas Darnell, Jared Miller and Benjamin Culkin
