.TH DISPATCH 1
.SH NAME
dispatch \- run all loaded processes 
.SH SYNOPSIS
.B mkpcb
[
.I "\-\-help"
]
.SH "DESCRIPTION"
Runs all processes in the ready queue
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Show a short usage message.
.SH NOTES
Nothing at the moment.
.SH AUTHOR
Lucas Darnell, Benjamin Culkin, and Jared Miller
