.TH EXIT 1
.SH NAME
help \- list commands, or get indepth help
.SH SYNOPSIS
.B exit
[
.I -h
]
[
.I --help
]

.SH "DESCRIPTION"
Triggers cleanup and terminates techOS
.SH OPTIONS
.TP
.B \-h, \-\-help
Show a short usage message.

.SH NOTES
Nothing in particular at the moment
.BR 
.SH AUTHOR
Lucas Darnell,Jared Miller and Benjamin Culkin
