.TH HELP 1
.SH NAME
help \- list commands, or get indepth help
.SH SYNOPSIS
.B help
[
.I \-h
]
[
.I \-\-help
]
.I "<program-name>"
.SH "DESCRIPTION"
Either lists all of the commands available to TechOS, or gives in-depth
help on a particular command.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show a short usage message.

.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Benjamin Culkin, Jared Miller, and Lucas Darnell
