.TH LS 1
.SH LS
ls \- show files and folders in the current, or specified, directory
.SH SYNOPSIS
.B ls
[
.I \-h
]
.SH "DESCRIPTION"
Shows the files and folders that are in the current directory, or in a directory that is specified by an option.
.SH OPTIONS
.TP
.B "\-a, \-\-author"
Print the version information of TechOS.
.TP
.B \-h, \-\-help
Show a short usage message
.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Jared Miller, Lucas Darnell and Benjamin Culkin
