.TH MKPCB 1
.SH NAME
mkadm \- create administrator account 
.SH SYNOPSIS
.B mkadm
[
.I \-h
]
[
.I "\-\-help"
]
.SH "DESCRIPTION"
Create an administrator account
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Show a short usage message.
.SH NOTES
None at the moment
.SH AUTHOR
Lucas Darnell, Benjamin Culkin, and Jared Miller
