.TH MKDIR 1
.SH MKDIR
mkdir \- creates a new folder in the current directory
.SH SYNOPSIS
.B mkdir
[
.I \-h
]

.SH "DESCRIPTION"
creates a new folder in the current directory
.SH OPTIONS
.TP
.B "\-a, \-\-author"
Print the version information of TechOS.
.TP
.B \-h, \-\-help
Show a short usage message
.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Jared Miller, Lucas Darnell and Benjamin Culkin
