.TH MKPCB 1
.SH NAME
mkpcb \- create PCB 
.SH SYNOPSIS
.B mkpcb
[
.I \-h
]
[
.I \-\-help
]
.I "<process-name> <priority>"
.SH "DESCRIPTION"
Executes commands read from a script line by line
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Show a short usage message.
.TP
.B "--class"
Set the process type. Valid ones are 'app'/'application' and 'system'
.SH NOTES
Process type is set to application by default
.SH AUTHOR
Lucas Darnell, Benjamin Culkin, and Jared Miller
