.TH MKPCB 1
.SH NAME
mkpcb \- create PCB 
.SH SYNOPSIS
.B mkpcb
[
.I \-h
]
[
.I \-\-help
]
.I "<process-name> <priority>"
.SH "DESCRIPTION"
Executes commands read from a script line by line
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Show a short usage message.
.B "--class_sys"
Set process type to system process
.B "--class_app"
Set process type to application process
.SH NOTES
Process type is set to application by default
.SH AUTHOR
Lucas Darnell, Benjamin Culkin, and Jared Miller
