.TH MKPCB 1
.SH NAME
mkpcb \- create PCB 
.SH SYNOPSIS
.B mkpcb
[
.I \-cnh
]
[
.I "-c|--class \f(BI(app|application)|(system|sys)\fP"
]
[
.I "\-\-help"
]
[
.I "-n|--name \f(BI<proc-name>\fP"
]
.I "<image-name> <priority>"
.SH "DESCRIPTION"
Create a process that can be executed.
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Show a short usage message.
.TP
.B "\-c, \-\-class"
Set the process type. Valid ones are 'app'/'application' and 'sys/system'
.TP
.B "\-n, \-\-name"
Set the process name.
.SH NOTES
Process type is set to application by default, are given the same name as their
image.
.SH AUTHOR
Lucas Darnell, Benjamin Culkin, and Jared Miller
