.TH MOO 1
.SH MOO
moo \- queries user on relevant behavioral information
.SH SYNOPSIS
.B moo
[
.I \-h
]

.SH "DESCRIPTION"
displays an image of 
.I Bos taurus
and queries relevant information from the user 
.SH OPTIONS
.TP
.B \-h, \-\-help
Show a short usage message
.SH NOTES
MOO
.SH AUTHOR
Jared Mooller, Lucas Darmool and Benjamoo Culkin
