.TH RM 1
.SH RM
rm \- removes a file
.SH SYNOPSIS
.B rm
[
.I \-h
]
[
.I \-\-help
]

.SH "DESCRIPTION"
Removes a file that is in the current directory.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show a short usage message
.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Jared Miller, Lucas Darnell and Benjamin Culkin
