.TH MKPCB 1
.SH NAME
rmadm \- remove Administrator account 
.SH SYNOPSIS
.B rmadm
[
.I \-h
]
[
.I "\-\-help"
]
.SH "DESCRIPTION"
Remove an administrator account 
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Show a short usage message.
.TP
.SH NOTES
Nothing at the moment
.SH AUTHOR
Lucas Darnell, Benjamin Culkin, and Jared Miller
