.TH RMDIR 1
.SH RMDIR
rmdir \- remove a directory
.SH SYNOPSIS
.B rmdir
[
.I \-h
]
[
.I \-\-help
]
.SH "DESCRIPTION"
Removes the directory specified
.SH OPTIONS
.TP
.B \-h, \-\-help
Show a short usage message
.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Jared Miller, Lucas Darnell and Benjamin Culkin
