.TH VERSION 1
.SH VERSION
version \- show current version, authors, and publish date
.SH SYNOPSIS
.B version
[
.I \-advh
]
[
.I \-\-author
]
[
.I \-\-date
]
[
.I \-\-help
]
[
.I \-\-version
]
.SH "DESCRIPTION"
Shows the current version of TechOS and also displays the authors and the
publishing date.
.SH OPTIONS
.TP
.B "\-a, \-\-author"
Print the version information of TechOS.
.TP
.B \-h, \-\-help
Show a short usage message
.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Jared Miller, Lucas Darnell and Benjamin Culkin
