.TH SCRIPT 1
.SH NAME
rmpcb \- remove a PCB 
.SH SYNOPSIS
.B rmpcb
[
.I \-h
]
[
.I \-\-help
]
.I "<process-name>|<process-id>"
.SH "DESCRIPTION"
Executes commands read from a script line by line
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Show a short usage message.
.SH NOTES
Nothing at the moment
.SH AUTHOR
Lucas Darnell, Benjamin Culkin, and Jared Miller
