.TH SCRIPT 1
.SH NAME
script \- Execute a script file 
.SH SYNOPSIS
.B script
[
.I \-h
]
[
.I \-\-help
]
.I "<file-name>"
.SH "DESCRIPTION"
Executes commands read from a script line by line
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Show a short usage message.
.SH NOTES
User will still need to provide input for commands that require it.
.SH AUTHOR
Lucas Darnell, Benjamin Culkin, and Jared Miller
