.TH SETDATE 1
.SH SETDATE
date \- set current date
.SH SYNOPSIS
.B setdate
.SH "DESCRIPTION"
.BR setdate
Update the system date according to the current date format. 
.SH OPTIONS
.TP
.B \-h, \-\-help
.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Jared Miller, Benjamin Culkin and Lucas Darnell
