.TH HELP 1
.SH HELP
help \- list commands, or get indepth help
.SH SYNOPSIS
.B help
.I "[program-name]"
.SH "DESCRIPTION"
.BR help
Help either lists all of the commands available to TechOS, or gives in-depth
help on a particular command.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.SH NOTES
Nothing in particular at the moment
.BR splitvt (1)
.SH AUTHOR
Jared Miller, Lucas Darnell and Benjamin Culkin
