.TH TOUCH 1
.SH TOUCH
touch \- creates a new file
.SH SYNOPSIS
.B touch
[
.I \-h
]
[
.I \-\-help
]
.SH "DESCRIPTION"
Creates a new file at the current directory.
.SH OPTIONS
.TP
.B "\-a, \-\-author"
Print the version information of TechOS.
.TP
.B \-h, \-\-help
Show a short usage message
.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Jared Miller, Lucas Darnell and Benjamin Culkin
