.TH VERSION 1
.SH VERSION
version \- show current version, authors, and publish date
.SH SYNOPSIS
.B version
.SH "DESCRIPTION"
.BR version
Version shows the current version of TechOS and also displays the authors and the
publishing date.
.SH NOTES
Nothing in particular at the moment
.SH AUTHOR
Jared Miller, Lucas Darnell and Benjamin Culkin
